discourse/discourse-kolide

app/controllers/webhooks_controller.rb
lib/alert.rb

The method "DateTime.parse" won't work for empty strings.
And fixed the minor linting issues.

FIX: use `to_datetime` method to parse "last reminded at" value.

---

lib/alert.rb
spec/lib/alert_spec.rb

Without `self.` prefix Ruby treating `last_reminded_at` as a local variable while calling it in code `last_reminded_at = remind_at`. So I'm using normal method format here to reduce confusion.

FIX: take 2 on stopping notification flood.

---

plugin.rb

We should use logger's warn method here since `Discourse.warn` demands one more parameter.

FIX: use `logger.warn` instead of `Discourse.warn` method.

---

config/locales/server.en.yml
lib/group_alert.rb
lib/user_alert.rb
spec/lib/user_alert_spec.rb

We can't update an existing post with empty body content. Instead, we're adding the default text now.

FIX: add default text for post body if issues not found.

---

lib/user_alert.rb

Currently, end users have no access to the issues in Kolide UI.

UX: remove link to the Kolide for device issues.

---

lib/user_alert.rb

Similar to the issue https://github.com/discourse/discourse-kolide/commit/ca1824d53156f8d61af23e16afafa7ce6882fc20

FIX: don't remind users when no issues found.

---

app/models/check.rb
app/models/device.rb
app/models/issue.rb
db/migrate/20211220131537_create_kolide_checks_table.rb
db/migrate/20211220142530_add_check_id_to_issues.rb
lib/user_alert.rb
plugin.rb
spec/fabricators/kolide_fabricator.rb
spec/lib/user_alert_spec.rb

ex: If we set `check.delay = 24` then users will get reminder for that check related issues after 1 day only.

FEATURE: sync Kolide checks & delay user reminders based on checks.

---

app/models/device.rb
spec/fixtures/reassigned.json
spec/requests/webhooks_controller_spec.rb
spec/spec_helper.rb

Previously, it returned the error since we retrieved the `user_id` in the wrong way.

FIX: treat webhook event payload data as hash to get user_id

---

db/post_migrate/20220104150337_populate_ip_addresses_field.rb
lib/group_alert.rb
plugin.rb
spec/fabricators/kolide_fabricator.rb
spec/lib/group_alert_spec.rb
spec/plugin_spec.rb

Now we will save last 10 IP addresses of users in custom field and we will match against the Kolide device IP addresses while creating the Kolide admins group PM alert.

FEATURE: save user IPs in custom field & match against device IPs

---

lib/api.rb
spec/requests/devices_controller_spec.rb

Previously, Kolide API returned an error while trying to assign a device owner using the PUT method. We should specify the header value 'Content-Type' => "application/json" to fix it.

FIX: `Content-Type` header is required for PUT methods on Kolide API.

---

app/models/device.rb
spec/models/device_spec.rb

Previously, the PM is not updated automatically. So it confuses the end users.

FEATURE: update user alert PM content after a device is destroyed.

---

plugin.rb

DEV: skip the attribute if `request` object is not available.

---

app/controllers/webhooks_controller.rb
app/models/device.rb
spec/fixtures/destroyed.json
spec/models/device_spec.rb
spec/requests/webhooks_controller_spec.rb

And also sync destroyed devices from Kolide via webhook.

FIX: skip PM alert update if user not found.

---

config/locales/server.en.yml
lib/user_alert.rb
spec/lib/user_alert_spec.rb

Without username unable to identify the PM recipients in Kolide helpers group inbox.

FEATURE: add username in user alert topic's title.

---

lib/group_alert.rb
spec/lib/group_alert_spec.rb

Previously, the notification which sent to the Kolide admin group users for the missing device assignment reason keep alerting them even after the device is assigned to someone.

UX: remove alert notification if issues are resolved in all devices.

---

lib/group_alert.rb
lib/user_alert.rb
plugin.rb
spec/lib/group_alert_spec.rb
spec/lib/user_alert_spec.rb

Previously, we used bookmarks for the user and group alerts. It created multiple notifications for a single alert in the interval given. Now the consolidation feature will remove the old notifications before creating new ones.

FEATURE: use notification consolidation feature to remove old notifications.

---

app/models/kolide/check.rb
app/models/kolide/device.rb
app/models/kolide/issue.rb
lib/api.rb
spec/fixtures/checks.json
spec/fixtures/devices.json
spec/fixtures/issues.json
spec/fixtures/issues_2.json
spec/kolide_spec.rb
spec/models/check_spec.rb
spec/models/device_spec.rb

Kolide's API response is limited to 100 items for GET methods. So we must perform multiple API calls to get all the items.

FIX: use "`cursor`" pagination param to fetch all the records from API.

---

assets/javascripts/discourse/initializers/extend-for-kolide.js
lib/application_controller_extension.rb
lib/user_extension.rb
plugin.rb
spec/requests/application_controller_spec.rb

Previously, we only checked the current IP address of the user to determine whether a device is onboarded or not. It creates problem when the IP address is not updated either in Kolide system or in Discourse. So, now we're including the old IP addresses from the `UserAuthTokenLog` table. Also, we're now creating a cookie to prevent repeated checking.

DEV: check old IPs with Kolide to determine onboarded devices.

---

assets/javascripts/discourse/initializers/extend-for-kolide.js
test/javascripts/acceptance/discourse-kolide-test.js

We don’t require installing kolide on mobile devices.

UX: hide non-onboarded device notice on mobile view.

---

assets/javascripts/discourse/initializers/extend-for-kolide.js
test/javascripts/acceptance/discourse-kolide-test.js

Previously, the code was wrongly moved inside the if condition where we will attach the button only if the device is not onboarded.

FIX: always attach recheck button when user is logged in.

---

assets/javascripts/discourse/initializers/extend-for-kolide.js

We previously set a 1-day delay which made the notices appear daily.

UX: increase non-onboarded device notice's dismiss duration to 1 week.

---

spec/requests/webhooks_controller_spec.rb

The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115

DEV: Replace deprecated queue_jobs site setting in tests

---

lib/user_alert.rb
spec/lib/user_alert_spec.rb

Previously, the notification which sent to the users for the open issues is keep alerting them even after those issues are resolved.

UX: remove user alert notification if all the issues are resolved.

---

assets/javascripts/discourse/initializers/extend-for-kolide.js
lib/application_controller_extension.rb

Also this change will decrease the dismiss duration for onboarding notice.

DEV: display the notice even if corresponding Kolide user ID is not available.

---

lib/application_controller_extension.rb

We are not installing Kolide on iPad and Chrome OS devices. So we shouldn't display the alert on browser.

UX: hide non-onboarded device alert on iPad & Chrome OS.

---

lib/application_controller_extension.rb
spec/requests/application_controller_spec.rb

Previously, once the `kolide_non_onboarded` cookie is created it won't be removed for a year or until onboarding that device.

DEV: delete `kolide_non_onboarded` cookie if onboarding not required.

---

config/locales/server.en.yml
config/settings.yml
lib/application_controller_extension.rb
spec/requests/application_controller_spec.rb

If you specify a value for  site setting then the onboarding notice will be displayed only for the members of that group. Else it will displayed to everyone when the setting is empty.

FEATURE: display onboarding notice only to group members in setting.

---

app/controllers/devices_controller.rb
assets/javascripts/discourse/controllers/preferences/kolide.js
assets/javascripts/discourse/routes/preferences-kolide.js
assets/javascripts/discourse/templates/preferences/kolide.hbs
config/locales/client.en.yml
lib/application_controller_extension.rb
spec/requests/application_controller_spec.rb
spec/requests/devices_controller_spec.rb

Sometimes we're unable to detect the mobile devices from their user agent to skip the Kolide onboarding. For example, in the latest iPadOS 13 Beta, Apple claimed desktop-class browsing in Safari. It seems Safari mimics macOS behavior and user agent. This commit gives the ability to users to choose whether the current device is mobile or not.

FEATURE: new checkbox to mark a device as mobile in onboarding

---

lib/user_alert.rb
spec/lib/user_alert_spec.rb

The previous check only would display the post body for "open issues"
without the delay check. Now that we have the upcoming issues and the
open issues section we need to still show the post body if there are
only "upcoming issues". Otherwise if we only have upcoming issues the
post body won't be displayed.
Follow up to: bb95792988137e3d2add4f5e0a2927bd2283aea0

FIX: Display post body when there are only upcoming issues

---

lib/user_alert.rb
spec/lib/user_alert_spec.rb

Follow up regression fix to bb95792988137e3d2add4f5e0a2927bd2283aea0
Resolved issues can be `resolved: true` OR `ignored: true`.

FIX: Resolved issues can be resolved or ignored

---

db/migrate/20241014102849_alter_kolide_ids_to_bigint.rb

The primary key is usually a bigint column, but the foreign key columns are usually of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.

DEV: Fix mismatched column types
